# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fileserve < Formula
  desc "Golang-based simple file server to serve static files of the current working directory"
  homepage "https://github.com/hupe1980/fileserve"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/fileserve/releases/download/v0.0.4/fileserve_Darwin_x86_64.tar.gz"
      sha256 "4e43366d30b29e4b295900dc3c3869b026ffdb16e02b7269ababd977f7bf2b36"

      def install
        bin.install "fileserve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/fileserve/releases/download/v0.0.4/fileserve_Darwin_arm64.tar.gz"
      sha256 "870d8acedeb0e35262c6954d74f2e54f7947b44ba4e41afe6d24f4e78be922d1"

      def install
        bin.install "fileserve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/fileserve/releases/download/v0.0.4/fileserve_Linux_armv6.tar.gz"
      sha256 "3fbc5a22bce19c515410e6e2982c82d93a0e1e543b77075e38334a4252607c71"

      def install
        bin.install "fileserve"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/fileserve/releases/download/v0.0.4/fileserve_Linux_x86_64.tar.gz"
      sha256 "32b36bc9b76fea2b764273a5aa8752784eb9209d4fa4b0c5921b3687f15b0d68"

      def install
        bin.install "fileserve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/fileserve/releases/download/v0.0.4/fileserve_Linux_arm64.tar.gz"
      sha256 "3f6bb9fbd199bc179965e490340399a1a770dbcfb70b98360438ee3a8790b4e3"

      def install
        bin.install "fileserve"
      end
    end
  end

  test do
    system "#{bin}/fileserve -v"
  end
end
